version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      DATASOURCES_BLOG_ADDR: postgres
      NODE_ENV: development
      PORT: 8090
    ports:
      - "8090:8090"
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules
    networks:
      - default

  postgres:
    image: postgres:11
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "blog" ]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: localhost
      POSTGRES_DB: blog_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
